### ISSUE TITLE
Local TMDL Summary

### ISSUE THREAD

**Issue by mvalentino** [rmeitl/Local-Report-Issue-Tracking#14]
There are 4 incorrect cell calulations in the Local TMDL Summary sheet. Update the cells listed below with the corresponding calulation:

Cell D38 
= SUM('Double Pipe Creek - FR - TP'!AF71,
'Double Pipe Creek - FR - TP'!BI71,
'Double Pipe Creek - FR - TP'!CL71,
'Double Pipe Creek - FR - TP'!DO71,
'Double Pipe Creek - FR - TP'!ER71,
'Double Pipe Creek - FR - TP'!FU71,
'Double Pipe Creek - FR - TP'!GX71,
'Double Pipe Creek - FR - TP'!IA71,
'Double Pipe Creek - FR - TP'!JD71,
'Double Pipe Creek - FR - TP'!KG71,
'Double Pipe Creek - FR - TP'!LJ71,
'Double Pipe Creek - FR - TP'!MM71,
'Double Pipe Creek - FR - TP'!NP71,
'Double Pipe Creek - FR - TP'!OS71)

Cell J59 
= SUM('Potomac MO County - MO - TSS'!M71,
'Potomac MO County - MO - TSS'!U71,
'Potomac MO County - MO - TSS'!AC71,
'Potomac MO County - MO - TSS'!AK71,
'Potomac MO County - MO - TSS'!AS71,
'Potomac MO County - MO - TSS'!BA71,
'Potomac MO County - MO - TSS'!BR71,
'Potomac MO County - MO - TSS'!CU71,
'Potomac MO County - MO - TSS'!DX71,
'Potomac MO County - MO - TSS'!FA71,
'Potomac MO County - MO - TSS'!GD71,
'Potomac MO County - MO - TSS'!HG71,
'Potomac MO County - MO - TSS'!IJ71,
'Potomac MO County - MO - TSS'!JM71,
'Potomac MO County - MO - TSS'!KP71,
'Potomac MO County - MO - TSS'!LS71,
'Potomac MO County - MO - TSS'!MV71,
'Potomac MO County - MO - TSS'!NY71,
'Potomac MO County - MO - TSS'!PB71,
'Potomac MO County - MO - TSS'!QE71)

Cell L59 
= SUM('Potomac MO County - MO - TSS'!BS71,
'Potomac MO County - MO - TSS'!CV71,
'Potomac MO County - MO - TSS'!DY71,
'Potomac MO County - MO - TSS'!FB71,
'Potomac MO County - MO - TSS'!GE71,
'Potomac MO County - MO - TSS'!HH71,
'Potomac MO County - MO - TSS'!IK71,
'Potomac MO County - MO - TSS'!JN71,
'Potomac MO County - MO - TSS'!KQ71,
'Potomac MO County - MO - TSS'!LT71,
'Potomac MO County - MO - TSS'!MW71,
'Potomac MO County - MO - TSS'!NZ71,
'Potomac MO County - MO - TSS'!PC71,
'Potomac MO County - MO - TSS'!QF71)

Cell M59 
= SUM('Potomac MO County - MO - TSS'!BT71,
'Potomac MO County - MO - TSS'!CW71,
'Potomac MO County - MO - TSS'!DZ71,
'Potomac MO County - MO - TSS'!FC71,
'Potomac MO County - MO - TSS'!GF71,
'Potomac MO County - MO - TSS'!HI71,
'Potomac MO County - MO - TSS'!IL71,
'Potomac MO County - MO - TSS'!JO71,
'Potomac MO County - MO - TSS'!KR71,
'Potomac MO County - MO - TSS'!LU71,
'Potomac MO County - MO - TSS'!MX71,
'Potomac MO County - MO - TSS'!OA71,
'Potomac MO County - MO - TSS'!PD71,
'Potomac MO County - MO - TSS'!QG71)

**Comment by rmeitl** [comment]
mistake in this issue - reopening as a new issue...
